"""empty message

Revision ID: 877330de89b5
Revises: 
Create Date: 2019-02-26 01:46:53.928749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877330de89b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('content_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_content_id'), 'posts', ['content_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('relationship_table',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tags_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tags_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship_table')
    op.drop_table('tags')
    op.drop_index(op.f('ix_posts_content_id'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
